name: communication_service
description: Communication Service
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

dependencies:
  dart_jsonwebtoken: ^2.12.1
  dio: ^5.3.3
  dotenv: ^4.2.0
  envied: ^0.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mailer: ^6.0.1
  logging: ^1.2.0
  postgres: ^2.6.1
  retry: ^3.1.2
  shelf: ^1.1.5
  shelf_router: ^1.1.4
  shelf_static: ^1.0.0
